apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: finpay-api-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: finpay-api-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key:      finpay/production
        property: JWT_SECRET
    - secretKey: DATABASE_URL
      remoteRef:
        key:      finpay/production
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key:      finpay/production
        property: REDIS_URL
    - secretKey: RABBITMQ_URL
      remoteRef:
        key:      finpay/production
        property: RABBITMQ_URL
