################################################################################
# Namespace — overridden per overlay
################################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: finpay-base   # patched per overlay to finpay-dev / finpay-staging / finpay-prod
  labels:
    app.kubernetes.io/managed-by: argocd
