################################################################################
# apps/finpay-api/base/serviceaccount.yaml
# The eks.amazonaws.com/role-arn annotation is patched per environment
################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: finpay-api
  annotations:
    # Overlays patch this to the actual IRSA role ARN
    eks.amazonaws.com/role-arn: REPLACE_WITH_IRSA_ROLE_ARN
automountServiceAccountToken: true
